# Generated by Django 5.0 on 2023-12-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=123, upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
