# Generated by Django 5.0 on 2023-12-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_post_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
    ]
