# Generated by Django 5.0 on 2023-12-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, unique=True, verbose_name='Slug'),
        ),
    ]
