# Generated by Django 5.0 on 2023-12-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_comment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(max_length=20, unique=True, verbose_name='Slug'),
        ),
    ]
